/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminMasterIndexRouteImport } from './routes/admin-master.index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AdminMasterDashboardRouteImport } from './routes/admin-master.dashboard'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppPlanosRouteImport } from './routes/_app/planos'
import { Route as AppNotificacoesRouteImport } from './routes/_app/notificacoes'
import { Route as AppModalidadesRouteImport } from './routes/_app/modalidades'
import { Route as AppHorariosRouteImport } from './routes/_app/horarios'
import { Route as AppGraduacoesRouteImport } from './routes/_app/graduacoes'
import { Route as AppEquipeRouteImport } from './routes/_app/equipe'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppAlunosRouteImport } from './routes/_app/alunos'
import { Route as AdminMasterTenantIdRouteImport } from './routes/admin-master.tenant.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMasterIndexRoute = AdminMasterIndexRouteImport.update({
  id: '/admin-master/',
  path: '/admin-master/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminMasterDashboardRoute = AdminMasterDashboardRouteImport.update({
  id: '/admin-master/dashboard',
  path: '/admin-master/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppModalidadesRoute = AppModalidadesRouteImport.update({
  id: '/modalidades',
  path: '/modalidades',
  getParentRoute: () => AppRoute,
} as any)
const AppHorariosRoute = AppHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AppRoute,
} as any)
const AppGraduacoesRoute = AppGraduacoesRouteImport.update({
  id: '/graduacoes',
  path: '/graduacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAlunosRoute = AppAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AppRoute,
} as any)
const AdminMasterTenantIdRoute = AdminMasterTenantIdRouteImport.update({
  id: '/admin-master/tenant/$id',
  path: '/admin-master/tenant/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alunos': typeof AppAlunosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/equipe': typeof AppEquipeRoute
  '/graduacoes': typeof AppGraduacoesRoute
  '/horarios': typeof AppHorariosRoute
  '/modalidades': typeof AppModalidadesRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/planos': typeof AppPlanosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/admin-master/dashboard': typeof AdminMasterDashboardRoute
  '/admin-master/': typeof AdminMasterIndexRoute
  '/admin-master/tenant/$id': typeof AdminMasterTenantIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alunos': typeof AppAlunosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/equipe': typeof AppEquipeRoute
  '/graduacoes': typeof AppGraduacoesRoute
  '/horarios': typeof AppHorariosRoute
  '/modalidades': typeof AppModalidadesRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/planos': typeof AppPlanosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/admin-master/dashboard': typeof AdminMasterDashboardRoute
  '/': typeof AppIndexRoute
  '/admin-master': typeof AdminMasterIndexRoute
  '/admin-master/tenant/$id': typeof AdminMasterTenantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/alunos': typeof AppAlunosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/equipe': typeof AppEquipeRoute
  '/_app/graduacoes': typeof AppGraduacoesRoute
  '/_app/horarios': typeof AppHorariosRoute
  '/_app/modalidades': typeof AppModalidadesRoute
  '/_app/notificacoes': typeof AppNotificacoesRoute
  '/_app/planos': typeof AppPlanosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/admin-master/dashboard': typeof AdminMasterDashboardRoute
  '/_app/': typeof AppIndexRoute
  '/admin-master/': typeof AdminMasterIndexRoute
  '/admin-master/tenant/$id': typeof AdminMasterTenantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/alunos'
    | '/configuracoes'
    | '/equipe'
    | '/graduacoes'
    | '/horarios'
    | '/modalidades'
    | '/notificacoes'
    | '/planos'
    | '/relatorios'
    | '/admin-master/dashboard'
    | '/admin-master/'
    | '/admin-master/tenant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/alunos'
    | '/configuracoes'
    | '/equipe'
    | '/graduacoes'
    | '/horarios'
    | '/modalidades'
    | '/notificacoes'
    | '/planos'
    | '/relatorios'
    | '/admin-master/dashboard'
    | '/'
    | '/admin-master'
    | '/admin-master/tenant/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/_app/alunos'
    | '/_app/configuracoes'
    | '/_app/equipe'
    | '/_app/graduacoes'
    | '/_app/horarios'
    | '/_app/modalidades'
    | '/_app/notificacoes'
    | '/_app/planos'
    | '/_app/relatorios'
    | '/admin-master/dashboard'
    | '/_app/'
    | '/admin-master/'
    | '/admin-master/tenant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminMasterDashboardRoute: typeof AdminMasterDashboardRoute
  AdminMasterIndexRoute: typeof AdminMasterIndexRoute
  AdminMasterTenantIdRoute: typeof AdminMasterTenantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-master/': {
      id: '/admin-master/'
      path: '/admin-master'
      fullPath: '/admin-master/'
      preLoaderRoute: typeof AdminMasterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin-master/dashboard': {
      id: '/admin-master/dashboard'
      path: '/admin-master/dashboard'
      fullPath: '/admin-master/dashboard'
      preLoaderRoute: typeof AdminMasterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos': {
      id: '/_app/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificacoes': {
      id: '/_app/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modalidades': {
      id: '/_app/modalidades'
      path: '/modalidades'
      fullPath: '/modalidades'
      preLoaderRoute: typeof AppModalidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/horarios': {
      id: '/_app/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof AppHorariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graduacoes': {
      id: '/_app/graduacoes'
      path: '/graduacoes'
      fullPath: '/graduacoes'
      preLoaderRoute: typeof AppGraduacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipe': {
      id: '/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alunos': {
      id: '/_app/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AppAlunosRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin-master/tenant/$id': {
      id: '/admin-master/tenant/$id'
      path: '/admin-master/tenant/$id'
      fullPath: '/admin-master/tenant/$id'
      preLoaderRoute: typeof AdminMasterTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAlunosRoute: typeof AppAlunosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppGraduacoesRoute: typeof AppGraduacoesRoute
  AppHorariosRoute: typeof AppHorariosRoute
  AppModalidadesRoute: typeof AppModalidadesRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlunosRoute: AppAlunosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppGraduacoesRoute: AppGraduacoesRoute,
  AppHorariosRoute: AppHorariosRoute,
  AppModalidadesRoute: AppModalidadesRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminMasterDashboardRoute: AdminMasterDashboardRoute,
  AdminMasterIndexRoute: AdminMasterIndexRoute,
  AdminMasterTenantIdRoute: AdminMasterTenantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
